version: '3'

#Volumes
volumes:
  dbdata_voyager:
    driver: local

#Docker Networks
networks:
  voyager-teste-network:
    driver: bridge

services:
  
  #PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: leandrocosta91/php
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - voyager-teste-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./:/var/www
    - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - voyager-teste-network

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: voyager_teste
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata_voyager:/var/lib/mysql
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - voyager-teste-network